www_韩国男星朴成勋在《鱿鱼游戏2》_扮演跨性别女性引争议.html:
  link: http://www.msn.com/zh-cn/news/other/%E9%9F%A9%E5%9B%BD%E7%94%B7%E6%98%9F%E6%9C%B4%E6%88%90%E5%8B%8B%E5%9C%A8-%E9%B1%BF%E9%B1%BC%E6%B8%B8%E6%88%8F2-%E6%89%AE%E6%BC%94%E8%B7%A8%E6%80%A7%E5%88%AB%E5%A5%B3%E6%80%A7%E5%BC%95%E4%BA%89%E8%AE%AE/ar-AA1vmNvr?apiversion=v2&noservercache=1&domshim=1&renderwebcomponents=1&wcseo=1&batchservertelemetry=1&noservertelemetry=1
  md5: 00ff4d9d1fbdb95d140607ed26aafd0d
  title: 韩国男星朴成勋在《鱿鱼游戏2》 扮演跨性别女性引争议
  snippet: 《鱿鱼游戏》第二季将于2024年12月26日在网飞播出。新一季不仅有原班人马，还加入许多新卡司。因《黑暗荣耀》走红的朴成勋也加入，他将饰演一名跨性别女性。
  visited_date: '2024-12-24 14:08:36'
atvnewsonline_跨性别议题.html:
  link: https://atvnewsonline.com/tag/%E8%B7%A8%E6%80%A7%E5%88%AB%E8%AE%AE%E9%A2%98/
  md5: 039842d4a2a3cea71fec8a61a60de821
  title: 跨性别议题
  snippet: 首页/跨性别议题. 跨性别议题. 国际 · 特朗普：美国仅认两性禁跨性别者参女子体育. 2024年12月23日12:30. 特朗普承诺上任首日推行新政策，包括禁止跨性别者参与女子体育，...
  visited_date: '2024-12-24 14:09:11'
atvnewsonline_特朗普：美国仅认两性_禁跨性别者参女子体育.html:
  link: https://atvnewsonline.com/world/%E7%89%B9%E6%9C%97%E6%99%AE%EF%BC%9A%E7%BE%8E%E5%9B%BD%E4%BB%85%E8%AE%A4%E4%B8%A4%E6%80%A7-%E7%A6%81%E8%B7%A8%E6%80%A7%E5%88%AB%E8%80%85%E5%8F%82%E5%A5%B3%E5%AD%90%E4%BD%93%E8%82%B2/
  md5: 8ba8ce9581732a4f8ae0b3fd0131addf
  title: 特朗普：美国仅认两性 禁跨性别者参女子体育
  snippet: 美国总统当选人特朗普12月22日（星期日）表示，他将在上任首日“停止跨性别精神错乱”，并承诺“不允许男性参与女子体育”，强调美国政府的官方政策将仅承认“男性和女性”两种...
  visited_date: '2024-12-24 14:10:14'
atvnewsonline_美参院推进国防法案_禁供军人子女性别肯定照护.html:
  link: https://atvnewsonline.com/world/%E7%BE%8E%E5%8F%82%E9%99%A2%E6%8E%A8%E8%BF%9B%E5%9B%BD%E9%98%B2%E6%B3%95%E6%A1%88-%E7%A6%81%E4%BE%9B%E5%86%9B%E4%BA%BA%E5%AD%90%E5%A5%B3%E6%80%A7%E5%88%AB%E8%82%AF%E5%AE%9A%E7%85%A7%E6%8A%A4/
  md5: 6c7a28e05c62ef3606d180f33d406fb1
  title: 美参院推进国防法案 禁供军人子女性别肯定照护
  snippet: 美国联邦参议院（United States Senate）星期一（12月16日）以压倒性多数推进一项总额达8950亿美元（约4兆令吉）的国防政策法案，其中包括禁止为军人跨性别子女提供“性别肯定...
  visited_date: '2024-12-24 14:10:43'
cn_中国首宗跨性别“扭转治疗”诉讼：原告获医院赔偿.html:
  link: https://cn.nytimes.com/china/20241211/transgender-conversion-china/
  md5: 5c7afbabfa51c068ec293f8c301ab2bd
  title: 中国首宗跨性别“扭转治疗”诉讼：原告获医院赔偿
  snippet: 公开跨性别者身份后，灵儿被父母送到医院关了三个月，被迫接受了包括多轮电击疗法在内的治疗。她对医院的起诉被受理被中国LGBTQ群体视为一场来之不易的胜利。
  visited_date: '2024-12-24 14:11:16'
